# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scpplugin/forms/ui_scpplugin.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ScpPlugin(object):
    def setupUi(self, ScpPlugin):
        ScpPlugin.setObjectName("ScpPlugin")
        ScpPlugin.resize(720, 618)
        self.gridLayout_2 = QtWidgets.QGridLayout(ScpPlugin)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.buttonBox = QtWidgets.QDialogButtonBox(ScpPlugin)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Help)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 1, 1, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(ScpPlugin)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_input = QtWidgets.QWidget()
        self.tab_input.setObjectName("tab_input")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_input)
        self.gridLayout.setObjectName("gridLayout")
        self.label_addPointLayer = QtWidgets.QLabel(self.tab_input)
        self.label_addPointLayer.setObjectName("label_addPointLayer")
        self.gridLayout.addWidget(self.label_addPointLayer, 0, 0, 1, 1)
        self.label_addPolygonLayer = QtWidgets.QLabel(self.tab_input)
        self.label_addPolygonLayer.setObjectName("label_addPolygonLayer")
        self.gridLayout.addWidget(self.label_addPolygonLayer, 2, 0, 1, 1)
        self.tableWidget_pointLayers = QtWidgets.QTableWidget(self.tab_input)
        self.tableWidget_pointLayers.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget_pointLayers.setColumnCount(5)
        self.tableWidget_pointLayers.setObjectName("tableWidget_pointLayers")
        self.tableWidget_pointLayers.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pointLayers.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pointLayers.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pointLayers.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pointLayers.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pointLayers.setHorizontalHeaderItem(4, item)
        self.tableWidget_pointLayers.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.tableWidget_pointLayers, 1, 0, 1, 2)
        self.comboBox_addPolygonLayer = QtWidgets.QComboBox(self.tab_input)
        self.comboBox_addPolygonLayer.setEditable(True)
        self.comboBox_addPolygonLayer.setObjectName("comboBox_addPolygonLayer")
        self.gridLayout.addWidget(self.comboBox_addPolygonLayer, 2, 1, 1, 1)
        self.tableWidget_polygonLayers = QtWidgets.QTableWidget(self.tab_input)
        self.tableWidget_polygonLayers.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget_polygonLayers.setColumnCount(4)
        self.tableWidget_polygonLayers.setObjectName("tableWidget_polygonLayers")
        self.tableWidget_polygonLayers.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_polygonLayers.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_polygonLayers.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_polygonLayers.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_polygonLayers.setHorizontalHeaderItem(3, item)
        self.tableWidget_polygonLayers.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.tableWidget_polygonLayers, 3, 0, 1, 2)
        self.comboBox_selectMPA = QtWidgets.QComboBox(self.tab_input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_selectMPA.sizePolicy().hasHeightForWidth())
        self.comboBox_selectMPA.setSizePolicy(sizePolicy)
        self.comboBox_selectMPA.setObjectName("comboBox_selectMPA")
        self.gridLayout.addWidget(self.comboBox_selectMPA, 5, 1, 1, 1)
        self.comboBox_addPointLayer = QtWidgets.QComboBox(self.tab_input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_addPointLayer.sizePolicy().hasHeightForWidth())
        self.comboBox_addPointLayer.setSizePolicy(sizePolicy)
        self.comboBox_addPointLayer.setEditable(True)
        self.comboBox_addPointLayer.setObjectName("comboBox_addPointLayer")
        self.gridLayout.addWidget(self.comboBox_addPointLayer, 0, 1, 1, 1)
        self.label_selectMPA = QtWidgets.QLabel(self.tab_input)
        self.label_selectMPA.setObjectName("label_selectMPA")
        self.gridLayout.addWidget(self.label_selectMPA, 5, 0, 1, 1)
        self.buttonBox_inputTab = QtWidgets.QDialogButtonBox(self.tab_input)
        self.buttonBox_inputTab.setStandardButtons(QtWidgets.QDialogButtonBox.Open|QtWidgets.QDialogButtonBox.Reset|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox_inputTab.setObjectName("buttonBox_inputTab")
        self.gridLayout.addWidget(self.buttonBox_inputTab, 10, 0, 1, 2)
        self.comboBox_selectLand = QtWidgets.QComboBox(self.tab_input)
        self.comboBox_selectLand.setEnabled(False)
        self.comboBox_selectLand.setObjectName("comboBox_selectLand")
        self.gridLayout.addWidget(self.comboBox_selectLand, 6, 1, 1, 1)
        self.checkBox_land = QtWidgets.QCheckBox(self.tab_input)
        self.checkBox_land.setObjectName("checkBox_land")
        self.gridLayout.addWidget(self.checkBox_land, 6, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.tab_input)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 7, 0, 1, 2)
        self.tabWidget.addTab(self.tab_input, "")
        self.tab_result = QtWidgets.QWidget()
        self.tab_result.setObjectName("tab_result")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_result)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_pointLayers = QtWidgets.QLabel(self.tab_result)
        self.label_pointLayers.setObjectName("label_pointLayers")
        self.verticalLayout_2.addWidget(self.label_pointLayers)
        self.tableWidget_pointLayersResult = QtWidgets.QTableWidget(self.tab_result)
        self.tableWidget_pointLayersResult.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_pointLayersResult.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget_pointLayersResult.setColumnCount(5)
        self.tableWidget_pointLayersResult.setObjectName("tableWidget_pointLayersResult")
        self.tableWidget_pointLayersResult.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pointLayersResult.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pointLayersResult.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pointLayersResult.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pointLayersResult.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pointLayersResult.setHorizontalHeaderItem(4, item)
        self.tableWidget_pointLayersResult.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.tableWidget_pointLayersResult)
        self.label_polygonLayers = QtWidgets.QLabel(self.tab_result)
        self.label_polygonLayers.setObjectName("label_polygonLayers")
        self.verticalLayout_2.addWidget(self.label_polygonLayers)
        self.tableWidget_polygonLayersResult = QtWidgets.QTableWidget(self.tab_result)
        self.tableWidget_polygonLayersResult.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_polygonLayersResult.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget_polygonLayersResult.setColumnCount(5)
        self.tableWidget_polygonLayersResult.setObjectName("tableWidget_polygonLayersResult")
        self.tableWidget_polygonLayersResult.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_polygonLayersResult.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_polygonLayersResult.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_polygonLayersResult.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_polygonLayersResult.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_polygonLayersResult.setHorizontalHeaderItem(4, item)
        self.tableWidget_polygonLayersResult.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.tableWidget_polygonLayersResult)
        self.widget = QtWidgets.QWidget(self.tab_result)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_MPAArea = QtWidgets.QLabel(self.widget)
        self.label_MPAArea.setObjectName("label_MPAArea")
        self.horizontalLayout.addWidget(self.label_MPAArea)
        self.label_MPAAreaValue = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_MPAAreaValue.sizePolicy().hasHeightForWidth())
        self.label_MPAAreaValue.setSizePolicy(sizePolicy)
        self.label_MPAAreaValue.setText("")
        self.label_MPAAreaValue.setObjectName("label_MPAAreaValue")
        self.horizontalLayout.addWidget(self.label_MPAAreaValue)
        self.verticalLayout_2.addWidget(self.widget)
        self.line_2 = QtWidgets.QFrame(self.tab_result)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.label_crsWarning = QtWidgets.QLabel(self.tab_result)
        self.label_crsWarning.setStyleSheet("QLabel { background: orange; border-radius: 5px; padding: 2px}")
        self.label_crsWarning.setWordWrap(True)
        self.label_crsWarning.setObjectName("label_crsWarning")
        self.verticalLayout_2.addWidget(self.label_crsWarning)
        self.label_unitsWarning = QtWidgets.QLabel(self.tab_result)
        self.label_unitsWarning.setStyleSheet("QLabel { background: cyan; border-radius: 5px; padding: 2px}")
        self.label_unitsWarning.setWordWrap(True)
        self.label_unitsWarning.setObjectName("label_unitsWarning")
        self.verticalLayout_2.addWidget(self.label_unitsWarning)
        self.label_mpaClipped = QtWidgets.QLabel(self.tab_result)
        self.label_mpaClipped.setStyleSheet("QLabel { background: cyan; border-radius: 5px; padding: 2px}")
        self.label_mpaClipped.setWordWrap(True)
        self.label_mpaClipped.setObjectName("label_mpaClipped")
        self.verticalLayout_2.addWidget(self.label_mpaClipped)
        self.buttonBox_resultTab = QtWidgets.QDialogButtonBox(self.tab_result)
        self.buttonBox_resultTab.setStandardButtons(QtWidgets.QDialogButtonBox.Save)
        self.buttonBox_resultTab.setObjectName("buttonBox_resultTab")
        self.verticalLayout_2.addWidget(self.buttonBox_resultTab)
        self.tabWidget.addTab(self.tab_result, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 2)

        self.retranslateUi(ScpPlugin)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(ScpPlugin)

    def retranslateUi(self, ScpPlugin):
        _translate = QtCore.QCoreApplication.translate
        ScpPlugin.setWindowTitle(_translate("ScpPlugin", "NIWA SCP Plugin"))
        self.label_addPointLayer.setText(_translate("ScpPlugin", "Add point layer:"))
        self.label_addPolygonLayer.setText(_translate("ScpPlugin", "Add polygon layer:"))
        item = self.tableWidget_pointLayers.horizontalHeaderItem(0)
        item.setText(_translate("ScpPlugin", "Name"))
        item = self.tableWidget_pointLayers.horizontalHeaderItem(1)
        item.setText(_translate("ScpPlugin", "Desired %"))
        item = self.tableWidget_pointLayers.horizontalHeaderItem(2)
        item.setText(_translate("ScpPlugin", "Quantifying field"))
        item = self.tableWidget_pointLayers.horizontalHeaderItem(3)
        item.setText(_translate("ScpPlugin", "Inv"))
        item = self.tableWidget_polygonLayers.horizontalHeaderItem(0)
        item.setText(_translate("ScpPlugin", "Name"))
        item = self.tableWidget_polygonLayers.horizontalHeaderItem(1)
        item.setText(_translate("ScpPlugin", "Desired %"))
        item = self.tableWidget_polygonLayers.horizontalHeaderItem(2)
        item.setText(_translate("ScpPlugin", "Inv"))
        self.label_selectMPA.setText(_translate("ScpPlugin", "Select MPA layer:"))
        self.checkBox_land.setText(_translate("ScpPlugin", "Clip with land layer:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_input), _translate("ScpPlugin", "Input"))
        self.label_pointLayers.setText(_translate("ScpPlugin", "Point layers:"))
        item = self.tableWidget_pointLayersResult.horizontalHeaderItem(0)
        item.setText(_translate("ScpPlugin", "Name"))
        item = self.tableWidget_pointLayersResult.horizontalHeaderItem(1)
        item.setText(_translate("ScpPlugin", "Total value"))
        item = self.tableWidget_pointLayersResult.horizontalHeaderItem(2)
        item.setText(_translate("ScpPlugin", "Desired %"))
        item = self.tableWidget_pointLayersResult.horizontalHeaderItem(3)
        item.setText(_translate("ScpPlugin", "Actual %"))
        item = self.tableWidget_pointLayersResult.horizontalHeaderItem(4)
        item.setText(_translate("ScpPlugin", "Difference"))
        self.label_polygonLayers.setText(_translate("ScpPlugin", "Polygon layers:"))
        item = self.tableWidget_polygonLayersResult.horizontalHeaderItem(0)
        item.setText(_translate("ScpPlugin", "Name"))
        item = self.tableWidget_polygonLayersResult.horizontalHeaderItem(1)
        item.setText(_translate("ScpPlugin", "Area"))
        item = self.tableWidget_polygonLayersResult.horizontalHeaderItem(2)
        item.setText(_translate("ScpPlugin", "Desired %"))
        item = self.tableWidget_polygonLayersResult.horizontalHeaderItem(3)
        item.setText(_translate("ScpPlugin", "Actual %"))
        item = self.tableWidget_polygonLayersResult.horizontalHeaderItem(4)
        item.setText(_translate("ScpPlugin", "Difference"))
        self.label_MPAArea.setText(_translate("ScpPlugin", "MPA area:"))
        self.label_crsWarning.setText(_translate("ScpPlugin", "<html><head/><body><p><span style=\" font-weight:600;\">Warning</span>: the input layer CRS differ and on the fly CRS transformations are disabled. The analysis results are likely inaccurate.</p></body></html>"))
        self.label_unitsWarning.setText(_translate("ScpPlugin", "<html><head/><body><p><span style=\" font-weight:600;\">Note</span>: For areas to be displayed in square kilometers, on the fly CRS transformations need to be enabled and an appropriate ellipsoid selected in <span style=\" font-style:italic;\">Settings-&gt;Project Properties-&gt;General</span>.</p></body></html>"))
        self.label_mpaClipped.setText(_translate("ScpPlugin", "<html><head/><body><p><span style=\" font-weight:600;\">Note</span>: the MPA layer overlaps with the land layer, and the clipped MPA geometry was used for the analysis.</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_result), _translate("ScpPlugin", "Result"))

