# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_scpplugin.ui'
#
# Created: Wed Apr 16 11:59:45 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ScpPlugin(object):
    def setupUi(self, ScpPlugin):
        ScpPlugin.setObjectName(_fromUtf8("ScpPlugin"))
        ScpPlugin.resize(720, 618)
        self.gridLayout_2 = QtGui.QGridLayout(ScpPlugin)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.buttonBox = QtGui.QDialogButtonBox(ScpPlugin)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Help)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_2.addWidget(self.buttonBox, 1, 1, 1, 1)
        self.tabWidget = QtGui.QTabWidget(ScpPlugin)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_input = QtGui.QWidget()
        self.tab_input.setObjectName(_fromUtf8("tab_input"))
        self.gridLayout = QtGui.QGridLayout(self.tab_input)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_addPointLayer = QtGui.QLabel(self.tab_input)
        self.label_addPointLayer.setObjectName(_fromUtf8("label_addPointLayer"))
        self.gridLayout.addWidget(self.label_addPointLayer, 0, 0, 1, 1)
        self.label_addPolygonLayer = QtGui.QLabel(self.tab_input)
        self.label_addPolygonLayer.setObjectName(_fromUtf8("label_addPolygonLayer"))
        self.gridLayout.addWidget(self.label_addPolygonLayer, 2, 0, 1, 1)
        self.tableWidget_pointLayers = QtGui.QTableWidget(self.tab_input)
        self.tableWidget_pointLayers.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tableWidget_pointLayers.setColumnCount(5)
        self.tableWidget_pointLayers.setObjectName(_fromUtf8("tableWidget_pointLayers"))
        self.tableWidget_pointLayers.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pointLayers.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pointLayers.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pointLayers.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pointLayers.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pointLayers.setHorizontalHeaderItem(4, item)
        self.tableWidget_pointLayers.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.tableWidget_pointLayers, 1, 0, 1, 2)
        self.comboBox_addPolygonLayer = QtGui.QComboBox(self.tab_input)
        self.comboBox_addPolygonLayer.setEditable(True)
        self.comboBox_addPolygonLayer.setObjectName(_fromUtf8("comboBox_addPolygonLayer"))
        self.gridLayout.addWidget(self.comboBox_addPolygonLayer, 2, 1, 1, 1)
        self.tableWidget_polygonLayers = QtGui.QTableWidget(self.tab_input)
        self.tableWidget_polygonLayers.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tableWidget_polygonLayers.setColumnCount(4)
        self.tableWidget_polygonLayers.setObjectName(_fromUtf8("tableWidget_polygonLayers"))
        self.tableWidget_polygonLayers.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_polygonLayers.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_polygonLayers.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_polygonLayers.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_polygonLayers.setHorizontalHeaderItem(3, item)
        self.tableWidget_polygonLayers.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.tableWidget_polygonLayers, 3, 0, 1, 2)
        self.comboBox_selectMPA = QtGui.QComboBox(self.tab_input)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_selectMPA.sizePolicy().hasHeightForWidth())
        self.comboBox_selectMPA.setSizePolicy(sizePolicy)
        self.comboBox_selectMPA.setObjectName(_fromUtf8("comboBox_selectMPA"))
        self.gridLayout.addWidget(self.comboBox_selectMPA, 5, 1, 1, 1)
        self.comboBox_addPointLayer = QtGui.QComboBox(self.tab_input)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_addPointLayer.sizePolicy().hasHeightForWidth())
        self.comboBox_addPointLayer.setSizePolicy(sizePolicy)
        self.comboBox_addPointLayer.setEditable(True)
        self.comboBox_addPointLayer.setObjectName(_fromUtf8("comboBox_addPointLayer"))
        self.gridLayout.addWidget(self.comboBox_addPointLayer, 0, 1, 1, 1)
        self.label_selectMPA = QtGui.QLabel(self.tab_input)
        self.label_selectMPA.setObjectName(_fromUtf8("label_selectMPA"))
        self.gridLayout.addWidget(self.label_selectMPA, 5, 0, 1, 1)
        self.buttonBox_inputTab = QtGui.QDialogButtonBox(self.tab_input)
        self.buttonBox_inputTab.setStandardButtons(QtGui.QDialogButtonBox.Open|QtGui.QDialogButtonBox.Reset|QtGui.QDialogButtonBox.Save)
        self.buttonBox_inputTab.setObjectName(_fromUtf8("buttonBox_inputTab"))
        self.gridLayout.addWidget(self.buttonBox_inputTab, 10, 0, 1, 2)
        self.comboBox_selectLand = QtGui.QComboBox(self.tab_input)
        self.comboBox_selectLand.setEnabled(False)
        self.comboBox_selectLand.setObjectName(_fromUtf8("comboBox_selectLand"))
        self.gridLayout.addWidget(self.comboBox_selectLand, 6, 1, 1, 1)
        self.checkBox_land = QtGui.QCheckBox(self.tab_input)
        self.checkBox_land.setObjectName(_fromUtf8("checkBox_land"))
        self.gridLayout.addWidget(self.checkBox_land, 6, 0, 1, 1)
        self.line = QtGui.QFrame(self.tab_input)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 7, 0, 1, 2)
        self.tabWidget.addTab(self.tab_input, _fromUtf8(""))
        self.tab_result = QtGui.QWidget()
        self.tab_result.setObjectName(_fromUtf8("tab_result"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_result)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_pointLayers = QtGui.QLabel(self.tab_result)
        self.label_pointLayers.setObjectName(_fromUtf8("label_pointLayers"))
        self.verticalLayout_2.addWidget(self.label_pointLayers)
        self.tableWidget_pointLayersResult = QtGui.QTableWidget(self.tab_result)
        self.tableWidget_pointLayersResult.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget_pointLayersResult.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tableWidget_pointLayersResult.setColumnCount(5)
        self.tableWidget_pointLayersResult.setObjectName(_fromUtf8("tableWidget_pointLayersResult"))
        self.tableWidget_pointLayersResult.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pointLayersResult.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pointLayersResult.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pointLayersResult.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pointLayersResult.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pointLayersResult.setHorizontalHeaderItem(4, item)
        self.tableWidget_pointLayersResult.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.tableWidget_pointLayersResult)
        self.label_polygonLayers = QtGui.QLabel(self.tab_result)
        self.label_polygonLayers.setObjectName(_fromUtf8("label_polygonLayers"))
        self.verticalLayout_2.addWidget(self.label_polygonLayers)
        self.tableWidget_polygonLayersResult = QtGui.QTableWidget(self.tab_result)
        self.tableWidget_polygonLayersResult.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget_polygonLayersResult.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tableWidget_polygonLayersResult.setColumnCount(5)
        self.tableWidget_polygonLayersResult.setObjectName(_fromUtf8("tableWidget_polygonLayersResult"))
        self.tableWidget_polygonLayersResult.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_polygonLayersResult.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_polygonLayersResult.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_polygonLayersResult.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_polygonLayersResult.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_polygonLayersResult.setHorizontalHeaderItem(4, item)
        self.tableWidget_polygonLayersResult.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.tableWidget_polygonLayersResult)
        self.widget = QtGui.QWidget(self.tab_result)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_MPAArea = QtGui.QLabel(self.widget)
        self.label_MPAArea.setObjectName(_fromUtf8("label_MPAArea"))
        self.horizontalLayout.addWidget(self.label_MPAArea)
        self.label_MPAAreaValue = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_MPAAreaValue.sizePolicy().hasHeightForWidth())
        self.label_MPAAreaValue.setSizePolicy(sizePolicy)
        self.label_MPAAreaValue.setText(_fromUtf8(""))
        self.label_MPAAreaValue.setObjectName(_fromUtf8("label_MPAAreaValue"))
        self.horizontalLayout.addWidget(self.label_MPAAreaValue)
        self.verticalLayout_2.addWidget(self.widget)
        self.line_2 = QtGui.QFrame(self.tab_result)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_2.addWidget(self.line_2)
        self.label_crsWarning = QtGui.QLabel(self.tab_result)
        self.label_crsWarning.setStyleSheet(_fromUtf8("QLabel { background: orange; border-radius: 5px; padding: 2px}"))
        self.label_crsWarning.setWordWrap(True)
        self.label_crsWarning.setObjectName(_fromUtf8("label_crsWarning"))
        self.verticalLayout_2.addWidget(self.label_crsWarning)
        self.label_unitsWarning = QtGui.QLabel(self.tab_result)
        self.label_unitsWarning.setStyleSheet(_fromUtf8("QLabel { background: cyan; border-radius: 5px; padding: 2px}"))
        self.label_unitsWarning.setWordWrap(True)
        self.label_unitsWarning.setObjectName(_fromUtf8("label_unitsWarning"))
        self.verticalLayout_2.addWidget(self.label_unitsWarning)
        self.label_mpaClipped = QtGui.QLabel(self.tab_result)
        self.label_mpaClipped.setStyleSheet(_fromUtf8("QLabel { background: cyan; border-radius: 5px; padding: 2px}"))
        self.label_mpaClipped.setWordWrap(True)
        self.label_mpaClipped.setObjectName(_fromUtf8("label_mpaClipped"))
        self.verticalLayout_2.addWidget(self.label_mpaClipped)
        self.buttonBox_resultTab = QtGui.QDialogButtonBox(self.tab_result)
        self.buttonBox_resultTab.setStandardButtons(QtGui.QDialogButtonBox.Save)
        self.buttonBox_resultTab.setObjectName(_fromUtf8("buttonBox_resultTab"))
        self.verticalLayout_2.addWidget(self.buttonBox_resultTab)
        self.tabWidget.addTab(self.tab_result, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 2)

        self.retranslateUi(ScpPlugin)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(ScpPlugin)

    def retranslateUi(self, ScpPlugin):
        ScpPlugin.setWindowTitle(_translate("ScpPlugin", "NIWA SCP Plugin", None))
        self.label_addPointLayer.setText(_translate("ScpPlugin", "Add point layer:", None))
        self.label_addPolygonLayer.setText(_translate("ScpPlugin", "Add polygon layer:", None))
        item = self.tableWidget_pointLayers.horizontalHeaderItem(0)
        item.setText(_translate("ScpPlugin", "Name", None))
        item = self.tableWidget_pointLayers.horizontalHeaderItem(1)
        item.setText(_translate("ScpPlugin", "Desired %", None))
        item = self.tableWidget_pointLayers.horizontalHeaderItem(2)
        item.setText(_translate("ScpPlugin", "Quantifying field", None))
        item = self.tableWidget_pointLayers.horizontalHeaderItem(3)
        item.setText(_translate("ScpPlugin", "Inv", None))
        item = self.tableWidget_polygonLayers.horizontalHeaderItem(0)
        item.setText(_translate("ScpPlugin", "Name", None))
        item = self.tableWidget_polygonLayers.horizontalHeaderItem(1)
        item.setText(_translate("ScpPlugin", "Desired %", None))
        item = self.tableWidget_polygonLayers.horizontalHeaderItem(2)
        item.setText(_translate("ScpPlugin", "Inv", None))
        self.label_selectMPA.setText(_translate("ScpPlugin", "Select MPA layer:", None))
        self.checkBox_land.setText(_translate("ScpPlugin", "Clip with land layer:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_input), _translate("ScpPlugin", "Input", None))
        self.label_pointLayers.setText(_translate("ScpPlugin", "Point layers:", None))
        item = self.tableWidget_pointLayersResult.horizontalHeaderItem(0)
        item.setText(_translate("ScpPlugin", "Name", None))
        item = self.tableWidget_pointLayersResult.horizontalHeaderItem(1)
        item.setText(_translate("ScpPlugin", "Total value", None))
        item = self.tableWidget_pointLayersResult.horizontalHeaderItem(2)
        item.setText(_translate("ScpPlugin", "Desired %", None))
        item = self.tableWidget_pointLayersResult.horizontalHeaderItem(3)
        item.setText(_translate("ScpPlugin", "Actual %", None))
        item = self.tableWidget_pointLayersResult.horizontalHeaderItem(4)
        item.setText(_translate("ScpPlugin", "Difference", None))
        self.label_polygonLayers.setText(_translate("ScpPlugin", "Polygon layers:", None))
        item = self.tableWidget_polygonLayersResult.horizontalHeaderItem(0)
        item.setText(_translate("ScpPlugin", "Name", None))
        item = self.tableWidget_polygonLayersResult.horizontalHeaderItem(1)
        item.setText(_translate("ScpPlugin", "Area", None))
        item = self.tableWidget_polygonLayersResult.horizontalHeaderItem(2)
        item.setText(_translate("ScpPlugin", "Desired %", None))
        item = self.tableWidget_polygonLayersResult.horizontalHeaderItem(3)
        item.setText(_translate("ScpPlugin", "Actual %", None))
        item = self.tableWidget_polygonLayersResult.horizontalHeaderItem(4)
        item.setText(_translate("ScpPlugin", "Difference", None))
        self.label_MPAArea.setText(_translate("ScpPlugin", "MPA area:", None))
        self.label_crsWarning.setText(_translate("ScpPlugin", "<html><head/><body><p><span style=\" font-weight:600;\">Warning</span>: the input layer CRS differ and on the fly CRS transformations are disabled. The analysis results are likely inaccurate.</p></body></html>", None))
        self.label_unitsWarning.setText(_translate("ScpPlugin", "<html><head/><body><p><span style=\" font-weight:600;\">Note</span>: For areas to be displayed in square kilometers, on the fly CRS transformations need to be enabled and an appropriate ellipsoid selected in <span style=\" font-style:italic;\">Settings-&gt;Project Properties-&gt;General</span>.</p></body></html>", None))
        self.label_mpaClipped.setText(_translate("ScpPlugin", "<html><head/><body><p><span style=\" font-weight:600;\">Note</span>: the MPA layer overlaps with the land layer, and the clipped MPA geometry was used for the analysis.</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_result), _translate("ScpPlugin", "Result", None))

